###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "randomEmail@gmail.com",
    "password": "HelloWorld123"
}

###
GET http://localhost:8080/api/v1/questions
###

DELETE http://localhost:8080/api/v1/auth/user/1

###

PUT http://localhost:8080/api/v1/user/1/complete-today

###

GET http://localhost:8080/auth/api/v1/user/1

###

POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
    "email": "Ryanqu27@gmail.com",
    "passwordHash": "7!@#FJ10129*&!@#-0",
    "currentStreak": 1,
    "longestStreak": 5,
    "lastCompletedDate": "2024-05-20"
}

###
GET http://localhost:8080/api/v1/user/1

###
