spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5332/reasonly
spring.datasource.password=password
spring.datasource.username=ryanqu27
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true